Repository FluidSynth/fluidsynth, pull requests merged in 2018-03, with the labels that each got.

#346 Additional build tests for CI
  .appveyor-vcpkg.yml
  .appveyor.yml
  .travis.yml
  CMakeLists.txt
  README.md
Labels: enhancement

#352 :bug: fix the index 'i' to 'i2' in delete_fluid_midi_router_rule (new…
  src/midi/fluid_midi_router.c
Labels: bug

#355 Build fixes.
  src/bindings/fluid_lash.c
  src/drivers/fluid_dsound.c
  src/utils/fluidsynth_priv.h
Labels: buildsystem

#354 Fix sample check and SF3 soundfont loading
  src/sfloader/fluid_defsfont.c
Labels: bug

#358 fix bug on channel disabled
  src/synth/fluid_synth.c
Labels: bug
