Repository FluidSynth/fluidsynth, pull requests merged in 2018-12, with the labels that each got.

#406 Convex shape for modEnv
  src/rvoice/fluid_rvoice.c
Labels: bug

#466 Waveout driver
  CMakeLists.txt
  cmake_admin/report.cmake
  src/CMakeLists.txt
  src/config.cmake
  src/drivers/fluid_adriver.c
  src/drivers/fluid_adriver.h
  src/drivers/fluid_waveout.c
Labels: enhancement

#478 Sdl2 driver
  CMakeLists.txt
  cmake_admin/FindSDL2.cmake
  cmake_admin/report.cmake
  doc/fluidsettings.xml
  doc/fluidsynth-v20-devdoc.txt
  src/CMakeLists.txt
  src/config.cmake
  src/drivers/fluid_adriver.c
  src/drivers/fluid_adriver.h
  src/drivers/fluid_aufile.c
  src/drivers/fluid_sdl2.c
Labels: enhancement

#484 Cross Compilation Fixes
  CMakeLists.txt
  src/CMakeLists.txt
  src/config.cmake
  src/gentables/CMakeLists.txt
  src/synth/fluid_synth.c
  src/utils/fluidsynth_priv.h
Labels: bug, buildsystem

#487 Fix minor bug in lower_boundary_for_attenuation()
  src/sfloader/fluid_defsfont.c
  src/synth/fluid_mod.c
  src/synth/fluid_voice.c
Labels: bug
