Repository FluidSynth/fluidsynth, pull requests merged in 2020-01, with the labels that each got.

#606 CMakeLists.txt: use pkg-config to find readline
  CMakeLists.txt
Labels: buildsystem

#607 Workaround for jack sample rate mismatch
  src/drivers/fluid_adriver.c
  src/drivers/fluid_adriver.h
  src/drivers/fluid_jack.c
  src/utils/fluid_settings.c
  src/utils/fluid_settings.h
  test/CMakeLists.txt
  test/test_jack_obtaining_synth.c
Labels: bug

#611 Compile suitable demo files from doc/
  cmake_admin/FluidUnitTest.cmake
  doc/CMakeLists.txt
  doc/example.c
  doc/fluidsynth_register_adriver.c
Labels: enhancement
