Repository FluidSynth/fluidsynth, pull requests merged in 2022-09, with the labels that each got.

#1023 Extend MIDI auto connect
  doc/fluidsettings.xml
  src/drivers/fluid_alsa.c
  src/drivers/fluid_winmidi.c
Labels: enhancement

#1153 Prevent jack driver to auto-connect audio to MIDI ports
  src/drivers/fluid_jack.c
Labels: bug

#1152 Fix incorrect maximum excursion of modulators
  src/synth/fluid_mod.c
Labels: bug

#1154 Fix build against OSS 4.0 API
  src/drivers/fluid_oss.c
Labels: bug, buildsystem

#1158 Mix effects in parallel
  CMakeLists.txt
  src/rvoice/fluid_rvoice_mixer.c
Labels: enhancement

#1156 Add linear interpolation to convex and concave transfer functions
  src/utils/fluid_conv.c
Labels: enhancement
