Repository FluidSynth/fluidsynth, pull requests merged in 2024-10, with the labels that each got.

#1390 Add missing UTF8 conversion
  src/fluidsynth.c
Labels: bug

#1394 Fix discovery of Oboe
  .azure/azure-pipelines-android.yml
  cmake_admin/Findoboe.cmake
Labels: bug, buildsystem

#1404 Fix interpretation of '-' as pipe
  src/fluidsynth.c
Labels: bug

#1385 Set synth.device-id to 16 by default
  doc/recent_changes.txt
  src/synth/fluid_synth.c
Labels: enhancement

#1400 Add support for loop mode release
  src/rvoice/fluid_rvoice.c
  src/rvoice/fluid_rvoice.h
Labels: enhancement

#1409 Add support for absolute transform
  doc/recent_changes.txt
  include/fluidsynth/mod.h
  src/sfloader/fluid_defsfont.c
  src/synth/fluid_mod.c
  src/synth/fluid_mod.h
Labels: enhancement

#1346 Add support for AWE32 NRPNs
  src/rvoice/fluid_iir_filter.c
  src/sfloader/fluid_defsfont.c
  src/synth/fluid_chan.c
  src/synth/fluid_chan.h
  src/synth/fluid_mod.c
  src/synth/fluid_mod.h
  src/synth/fluid_synth.c
  src/synth/fluid_voice.c
  src/utils/fluid_conv.c
  src/utils/fluid_conv.h
Labels: enhancement

#1414 Enable ALSA support by default.
  CMakeLists.txt
  src/drivers/fluid_alsa.c
Labels: buildsystem

#1392 Fix bugs in modulator handling
  src/sfloader/fluid_defsfont.c
  src/synth/fluid_mod.c
  src/synth/fluid_voice.c
Labels: bug
